---
- name: Install Maven, Git, and Java
  hosts: g1
  become: yes  

  tasks:
    - name: Check the OS distribution
      debug:
        var: ansible_distribution

    - name: Install Git on CentOS
      yum:
        name: git
        state: present
      when: "'CentOS' in ansible_distribution"

    - name: Install Git on Ubuntu
      apt:
        name: git
        state: present
      when: "'Ubuntu' in ansible_distribution"

    - name: Install Git on Amazon Linux
      dnf:
        name: git
        state: present
      when: "'Amazon' in ansible_distribution"

    - name: Update APT package manager repositories cache
      command: apt-get update
      when: "'CentOS' in ansible_distribution or 'Ubuntu' in ansible_distribution  or 'Amazon' in ansible_distribution"

    - name: Install Apache Maven on Centos, Amazon, Ubuntu
      become: true
      get_url: url=https://dlcdn.apache.org/maven/maven-3/3.9.5/binaries/apache-maven-3.9.5-bin.tar.gz
      when: "'CentOS' in ansible_distribution or 'Ubuntu' in ansible_distribution  or 'Amazon' in ansible_distribution"

    - name: Untar Maven
      become: true 
      shell: chdir=/tmp creates=/opt/apache-maven-3.9.5 tar -zxf apache-maven-3.9.5-bin.tar.gz -C /opt
      when: "'CentOS' in ansible_distribution or 'Ubuntu' in ansible_distribution  or 'Amazon' in ansible_distribution"

    - name: Set MAVEN_HOME
      become: true
      lineinfile:
        dest: /etc/profile.d/maven.sh
        create: yes
        state: present
        mode: '0744'
        line: '{{ item }}'
      with_items:
      - 'export M2_HOME=/opt/apache-maven-3.9.5'
      - 'export MAVEN_HOME=/opt/apache-maven-3.9.5'
      - 'export PATH=${M2_HOME}/bin:${PATH}'
      when: "'CentOS' in ansible_distribution or 'Ubuntu' in ansible_distribution  or 'Amazon' in ansible_distribution"

    - name: Install Java on CentOS
      yum:
        name: java-1.8.0-openjdk
        state: present
      when: "'CentOS' in ansible_distribution"

    - name: Install Java on Ubuntu
      apt:
        name: openjdk-8-jdk
        state: present
      when: "'Ubuntu' in ansible_distribution"

    - name: Install Java on Amazon Linux
      dnf:
        name: java-1.8.0-openjdk
        state: present
      when: "'Amazon' in ansible_distribution"

...
