---
- name: Install Maven, Git, and Java
  hosts: g1
  become: yes
  tasks:
    - name: Check the OS distribution
      debug:
        var: ansible_distribution

    - name: Install Git on Amazon Linux
      dnf:
        name: git
        state: present
      when: "'Amazon' in ansible_distribution"

    - name: Update APT package manager repositories cache
      command: apt-get update
      when: ansible_facts['os_family'] == 'Debian'

    - name: Install Apache Maven
      get_url:
        url: https://dlcdn.apache.org/maven/maven-3/3.9.5/binaries/apache-maven-3.9.5-bin.tar.gz
        dest: /tmp/apache-maven-3.9.5-bin.tar.gz
      when: ansible_facts['os_family'] in ['RedHat', 'Debian']

    - name: Untar Maven
      unarchive:
        src: /tmp/apache-maven-3.9.5-bin.tar.gz
        dest: /opt
        remote_src: yes
      when: ansible_facts['os_family'] in ['RedHat', 'Debian']

    - name: Set MAVEN_HOME
      lineinfile:
        dest: /etc/profile.d/maven.sh
        line: "{{ item }}"
        create: yes
        state: present
      loop:
        - 'export M2_HOME=/opt/apache-maven-3.9.5'
        - 'export MAVEN_HOME=/opt/apache-maven-3.9.5'
        - 'export PATH=${M2_HOME}/bin:${PATH}'
      when: ansible_facts['os_family'] in ['RedHat', 'Debian']

    - name: Update dnf cache if needed.
      dnf: 
       update_cache: true

    - name: Download OpenJDK 11
      get_url:
        url: "https://download.java.net/java/GA/jdk11/9/GPL/openjdk-11.0.9_linux-x64_bin.tar.gz"
        dest: "/tmp/openjdk-11.tar.gz"

    - name: Extract OpenJDK 11
      ansible.builtin.unarchive:
        src: "/tmp/openjdk-11.tar.gz"
        dest: "/opt"
        remote_src: yes
        extra_opts: "--strip-components=1"
      notify:
        - Set Environment Variables

    - name: Set Environment Variables
      lineinfile:
        dest: /etc/environment
        line: "JAVA_HOME=/opt/jdk-11.0.9"
        state: present
      when: not ansible_check_mode
      notify:
        - Reload Environment
      become: yes

    - name: Reload Environment
      command: ". /etc/environment"
      when: not ansible_check_mode
      become: yes


...
