---
- name: Install Git, Apache Maven, and OpenJDK 11
  hosts: n3
  become: yes
  tasks:
    - name: Check the OS distribution
      debug:
        var: ansible_distribution

    - name: Install Git
      package:
        name: "{{ git_package }}"
        state: present

    - name: Install Apache Maven
      get_url:
        url: "{{ maven_url }}"
        dest: /tmp/apache-maven-3.9.5-bin.tar.gz
      when: ansible_distribution = Ubuntu

    - name: Untar Maven
      ansible.builtin.unarchive:
        src: /tmp/apache-maven-3.9.5-bin.tar.gz
        dest: /opt
        remote_src: yes
        extra_opts: "--strip-components=1"
      when: ansible_distribution in ['RedHat', 'Debian']

    - name: Set MAVEN_HOME
      lineinfile:
        dest: /etc/profile.d/maven.sh
        line: "{{ item }}"
        create: yes
        state: present
      loop:
        - 'export M2_HOME=/opt/apache-maven-3.9.5'
        - 'export MAVEN_HOME=/opt/apache-maven-3.9.5'
        - 'export PATH=${M2_HOME}/bin:${PATH}'
      when: ansible_distribution in ['RedHat', 'Debian']

    - name: Update package cache
      apt:
        update_cache: yes
      when:
        - ansible_facts['distribution'] == 'Ubuntu'

    - name: Install OpenJDK 11
      package:
        name: "{{ java_package }}"
        state: present

  vars:
    git_package: git
    maven_url: https://dlcdn.apache.org/maven/maven-3/3.9.5/binaries/apache-maven-3.9.5-bin.tar.gz
    java_package: openjdk-11-jdk

...
