---
- name: Install Java 11
  hosts: #n1
  become: yes

  tasks:
    - name: Install Java 11 on CentOS
      yum:
        name: java-11-openjdk
        state: present
      when: ansible_os_family == 'RedHat'

    - name: Install Java 11 on Amazon Linux
      yum:
        name: java-11-openjdk
        state: present
      when: ansible_os_family == 'Amazon'

    - name: Install Java 11 on Ubuntu
      apt:
        name: openjdk-11-jre
        state: present
      when: ansible_os_family == 'Debian'

    - name: Verify Java installation
      command: java -version
      register: java_version_output
      changed_when: false
      failed_when: "'11' not in java_version_output.stderr or 'OpenJDK' not in java_version_output.stderr"

    - name: Print Java version
      debug:
        msg: "Java version is {{ java_version_output.stderr }}"

...