---
  name: Install Git
  hosts: g2
  become: yes
  tasks:
    - name: Check the OS distribution
      debug:
        var: ansible_distribution

    - name: Install Git on CentOS
      yum:
        name: git
        state: present
      when: "ansible_distribution == 'CentOS'"

    - name: Install Git on Amazon Linux
      dnf:
        name: git
        state: present
      when: "ansible_distribution == 'Amazon'"

    - name: Install Git on Ubuntu
      apt:
        name: git
        state: present
      when: "ansible_distribution == 'Ubuntu'"

...       
