---
- name: Install Java
  hosts: g2
  become: yes
  tasks:
    - name: Check the OS distribution
      debug:
        var: ansible_distribution

    - name: Install Java on Amazon Linux
      dnf:
        name: java-11-amazon-corretto
        state: present
      when: ansible_distribution == 'Amazon'

...