- hosts: n5
  become: yes
  tasks:
    - name: Remove existing Tomcat directory if exists
      ansible.builtin.file:
        path: /opt/tomcat
        state: absent

    - name: Download latest Tomcat tarball
      ansible.builtin.get_url:
        url: "https://downloads.apache.org/tomcat/tomcat-{{ tomcat_version }}/bin/apache-tomcat-{{ tomcat_version }}.tar.gz"
        dest: "/tmp/apache-tomcat-{{ tomcat_version }}.tar.gz"
      vars:
        tomcat_version: "9.0.83"  # Change to the latest version

    - name: Extract Tomcat tarball
      ansible.builtin.unarchive:
        src: "/tmp/apache-tomcat-{{ tomcat_version }}.tar.gz"
        dest: "/opt/"
        remote_src: yes
        creates: "/opt/apache-tomcat-{{ tomcat_version }}/"

    - name: Set environment variables
      ansible.builtin.lineinfile:
        path: "/etc/environment"
        line: "CATALINA_HOME=/opt/apache-tomcat-{{ tomcat_version }}"
        create: yes

    - name: Systemd daemon reload
      ansible.builtin.command: "systemctl daemon-reload"
      become: yes
      when: ansible_distribution == 'Amazon'

...